### ISSUE TITLE
Question about units for stress tensor

### ISSUE THREAD

**Issue by vkg9** [fabrylab/pyTFM#1]
Hello! 

Thanks for uploading your code to github. This is not really an issue but more of a question. My name is Vivek Gupta, I'm a graduate student who was using your code. I used the example included in your python tutorial. The traction stresses from your code are outputting reasonable data. However, when I run the the monolayer stress microscopy the stress values I am seeing are on the order of 10^-8 Pa. I noticed when you calculate the mean stress you divide by the pixel size and 10^-6, which essentially gives stress values on the order of 10^-2 Pa, which are still very little. So I'm assuming I'm mis-interpretting the units somwhere. Would you be able to clarify? Or if the values you get are not what I mentioned above, what should the values be? I am not too familiar with coding in general, and Python as well, so just want to double check if I'm doing everything correctly. 

Thanks for your your help. 

Best, 
Vivek

**Comment by AndreasBauerGit** [comment]
Dear Vivek, 

Thank you for your question. I hope the following will clear it up:

First a general remark on units:

Tractions (also called traction forces or traction stresses) are forces-per-area acting on the surface of a material (such as the cell substrate). Thus the unit of tractions is N/m^2 (Pa). Stresses are forces acting inside of a material. In a real 3 dimensional material you can describe stresses by force-per-area acting on infinitesimal small cross-sectional planes in the material. This means that 3d stresses are also given in N/m^2. However, in Monolayer Stress Micrsocopy, the cells are modeled as a 2 dimensional material. The Monolayer Stresses resulting from these calculations are force-per-length acting on infinitesimal cross-sectional lines through the cell area. Thus, the unit of the Monolayer Stresses is N/m. One could consider to convert the Monolayer Stresses to 3d stresses by dividing with the cell height. Assuming a cell is 10 µm height, this would give you stresses in the order of 10^3  N/m^2 (Pa) instead of 10^-2 N/m that you mentioned. On the other hand, I don't think its necessary or very desirable to do that.

To sum up: Tractions and Monolayer Stresses have the units N/m^2 and N/m respectively. Thus, we expect to see difference in typically in the order of 10^6 (because cells are micrometer sized) between the two. 10^-2 N/m is a reasonable value for the Monolayer Stresses – we get similar values for the cells in our lab. 

Second:
I think there is some reason for confusion regarding the units in which deformations, tractions and stresses are saved to the "u.npy","v.npy","tx.npy","ty.npy" and "stress_tensor.npy" files:
Deformations (u.npy, v.npy) are save in pixel.
Tractions (tx.npy, ty.npy) are saved in N/m^2 (Pa).
Stresses (stress_tensor.npy) are saved in N/pixel.

In contrast the quantities for stresses and line tension reported in the "out.txt" files, such as the mean normal stress, are converted to N/m, hence the division by "10^-6" that you mentioned.
In the future, I guess I will change the unit of stress_tensor.npy to [N/m] to avoid further confusion. Also I added the correct units to all quantities in the out.txt files.

If I left anything unclear or have any further problems please let me!

with regards,

Andreas

**Comment by AndreasBauerGit** [comment]
So I just updated it: Stresses saved in stress_tensor.npy are now in N/m.
